from .base import *

BASIC_AUTH_USERNAME = 'Tqh7837eH6z2OgNU56t0QPJB'
BASIC_AUTH_PASSWORD = '@ssnYZT!1#21B$G£SCv'

JWT_SECRET_KEY = f"{SECRET_KEY}.9vEq2RakI!4o$Ka8@1r#h"

DATABASE["HOST"] = "localhost"

DEBUG = False